#!/usr/bin/env node
'use strict'


const program = require('commander');
program
    .version('0.0.1')
    .option('-n, --name <name>', 'Sets the network name')
    .option('-s, --subnet <subnet>', 'Sets the network subnet in CIDR format (192.168.1.0/24')
    .parse(process.argv);