#!/usr/bin/env node
'use strict';

const program = require('commander');

program
    .version('0.0.1')
    //.command('list','list networks')
    //.command('delete','delete network')
    .command('create','create network')
    //.command('update','update network')
    .parse(process.argv);